### ISSUE TITLE
Add new routing request parameter "maneuvers=true/false"

### ISSUE THREAD

**Issue by Rungee** [GIScience/openrouteservice-docs#10]
"maneuvers" parameter specifies whether maneuver element is included into step element or not.
Default value is false.

In json response, every maneuver element consists of the following elements:
**location** - The coordinate of the point where a maneuver takes place.
**bearing_before** - Specifies an azimuth angle (in degrees) of the direction right before the maneuver.
**bearing_after** - Specifies an azimuth angle (in degrees) of the direction right after the maneuver.

![image](https://user-images.githubusercontent.com/1660719/29419904-bb745cdc-8370-11e7-8f27-dcb0512b8af6.png)

**Comment by TheGreatRefrigerator** [comment]
Done in 0f3331736962dc80106211cd567e5b1119b30359
