### ISSUE TITLE
Add description for "attributes" parameter (Directions API).

### ISSUE THREAD

**Issue by Rungee** [GIScience/openrouteservice-docs#12]
The "attributes" parameter can take the following values:
1. detourfactor
2. percentage
3. avgspeed

Url example:
....preference=recommended&profile=cycling-regular&units=m&**attributes=avgspeed|detourfactor|percentage**

Note that detourfactor and percentage are only applied to route segments.

![image](https://user-images.githubusercontent.com/1660719/29610901-eba5917a-87fb-11e7-8aa2-4fb07f65a7f9.png)

**Comment by TheGreatRefrigerator** [comment]
closed with e73964be57aa489065bfee1e5bf4e1f345edb52e
