### ISSUE TITLE
Add information for border restrictions

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-docs#19]
The routing engine now allows the restriction of routes based on country borders. There are two options available: restrict by border type, and restrict by country. 

Restrict by border type
The user can use the avoid_borders parameter to instruct the system to avoid borders. There are two available values for this:

`avoid_borders:all` - this restricts the routing so that no borders are crossed
`avoid_borders:controlled` - this restricts the routing so that controlled borders are not crossed (i.e. USA - Canada) but open borders can be crossed (i.e. France - Germany)

`routes?coordinates=8.688301,49.404454%7C8.684266,49.404223&geometry=true&geometry_format=geojson&options={avoid_borders:controlled}&preference=fastest&profile=driving-car&units=m`

`avoid_countries:xxx` - this tells the system to not cross into the specified country/countries. xxx represents one or more country IDs, and when provided the route avoids crossing the border of those countries. If more than one country is to be avoided, then this can be achieved by passing a pipe delimited string of IDs.

`routes?coordinates=8.688301,49.404454%7C8.684266,49.404223&geometry=true&geometry_format=geojson&options={avoid_countries":"1|120"}&preference=fastest&profile=driving-car&units=m`

`avoid_borders:controlled` and `avoid_countries` can be used together. For example, passing `avoid_borders:controlled` and `avoid_countries:193` would allow passing between France and Germany, but would avoid crossing into Switzerland.

`routes?coordinates=8.688301,49.404454%7C8.684266,49.404223&geometry=true&geometry_format=geojson&options={"avoid_borders":"controlled", "avoid_countries":"193"}&preference=fastest&profile=driving-car&units=m`

**Comment by TimMcCauley** [comment]
Please also add the country lookup table to [README.md](https://github.com/GIScience/openrouteservice-docs/blob/master/README.md).

**Comment by rabidllama** [comment]
Also, this feature is only available for car and HGV profiles

**Comment by TimMcCauley** [comment]
@TheGreatRefrigerator @rabidllama can this be closed?

**Comment by TheGreatRefrigerator** [comment]
will close automatically once we merge to master with https://github.com/GIScience/openrouteservice-docs/commit/a927338cd18229259da0dce7ca49f69065e9e6db
