### ISSUE TITLE
Update wheelchair parameters

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-docs#30]
For the enhanced wheelchair profile, some parameters have been altered (i.e. maximum_sloped_kerb is now used rather than maximum_sloped_curb to better reflect OSM tags). These need to be reflected in the docs when the ors core is updated.

**Comment by TheGreatRefrigerator** [comment]
closed with 9361fd0fd7ab7d832ea4627b6d3f0f8ba1edaab4
