### ISSUE TITLE
QGIS isochrone layer ID reference

### ISSUE THREAD

**Issue by sccowl** [GIScience/openrouteservice-docs#32]
Also posted on google groups, so apologies if this is in wrong place.

When using the QGIS plugin to 'use layer' under the isochrone menu.  The resulting isochrone shapefiles that are returned have three fields

- AAMINS - The minutes used to create the shape
- AAMODE - The method of transport used
- plus GEOM, with the geometry of the Isochrone shapefile.

I'd like to join back to the source layer to I can identify and label each isochrone. However, there doesn't seem to be any reference created that links back to the original input.

At the moment I can't see anyway to do this apart from separating into individual shapefiles, which defeats the object of using the layers function and isn't really practical as I have 100's of isochrones to create.

Is there a way to identify and link the ischrones back to the source location centroid.

**Comment by TimMcCauley** [comment]
@sccowl if this issue is still relevant, please add it to the corresponding section on https://ask.openrouteservice.org
