### ISSUE TITLE
Description of `smoothing` parameter does not reflect the actual implementation

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-docs#35]
The [current description](https://github.com/GIScience/openrouteservice-docs/blob/83bf4742fb7e69fff6406f302d499928e7fb77a1/swagger.yml#L1766=L1769) says that smoothing, which is the factor in `(smoothing_factor * maximum_radius_of_isochrone) / 10`, takes values in the range of `(0.0, 1.0)`. However, this is different from how this parameter actually works in two ways:

1. It [is allowed](https://github.com/GIScience/openrouteservice/blob/bf61cfeecbf80a9b3da8631de4616b3e05eda89c/openrouteservice/src/main/java/heigit/ors/services/isochrones/requestprocessors/json/JsonIsochroneRequestParser.java#L445) to take values in the range of `(0.0, 100.0)` rather than `(0.0, 1.0)`.

2. The dividing factor in the [equation used to compute the threshold value](https://github.com/GIScience/openrouteservice/blob/bf61cfeecbf80a9b3da8631de4616b3e05eda89c/openrouteservice/src/main/java/heigit/ors/isochrones/builders/concaveballs/ConcaveBallsIsochroneMapBuilder.java#L200) is `100` rather than `10`.

**Comment by TimMcCauley** [comment]
@rabidllama @TheGreatRefrigerator is this resolved?

**Comment by rabidllama** [comment]
doesn't seem to have been yet. Need to look at it to see if changes are needed in both the docs and the code
