### ISSUE TITLE
Speed in France, rural areas has been decreased to 80km/h

### ISSUE THREAD

**Issue by gorille** [GIScience/openrouteservice-docs#36]
The documentation here mentions that the speed in rural areas of france is 90 km/h, which is the old one. The new one is 80 km/h.

the data is here : https://github.com/GIScience/openrouteservice-docs#country-speed-sets

I don't know if the adjustment also has to be made in the code to reflect the change.

**Comment by TimMcCauley** [comment]
@gorille sorry for responding with such a delay - could you please add this also to https://github.com/GIScience/openrouteservice as an issue that is is also handled in the core logic? I will merge #37 once we have implemented it. Thanks a bunch!

**Comment by gorille** [comment]
@TimMcCauley that's done ! see [here](https://github.com/GIScience/openrouteservice/issues/355)
