### ISSUE TITLE
vehicle types full list

### ISSUE THREAD

**Issue by Benetzz** [GIScience/openrouteservice-docs#40]
On the docs, I found: 

`vehicle_type (for profile=driving-hgv only): hgv,bus,agricultural,delivery,forestry and goods.`

What are all the vehicle types available? On the website I can choose between a lot of vehicle types, but I can't find the full list here. 

Also, is there a misstype the "vehcile_type" on the examples sections?

Thankyou

**Comment by TimMcCauley** [comment]
Greetings @Benetzz please use the following link for further details:

https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/post

Thank you
