### ISSUE TITLE
Incorrect name/value for waycategory ferry and unpaved_road

### ISSUE THREAD

**Issue by amoncaldas** [GIScience/openrouteservice-docs#45]
The documentation states that among the possible values for `waycategory` '8' is for  'unpaved_road' and  '4' is for 'ferry'. But after checking the results visually on a map for places/routes it is clear that actually `8` is for `ferry` and  `4` is for `unpaved_road`.

**Comment by TheGreatRefrigerator** [comment]
closed in https://github.com/GIScience/openrouteservice-docs/pull/46/commits/300474578a0082bc68d9b973bad549db168f768c
