### ISSUE TITLE
What unit does distance use?

### ISSUE THREAD

**Issue by UnicornsOnLSD** [GIScience/openrouteservice-docs#48]
I'm using OpenRouteService with the JS API to get navigation data between two points and I want to use the distance value (in summary) to show the total distance of the route. I'm assuming that it's in meters, but I just wanted to make sure.

**Comment by TheGreatRefrigerator** [comment]
This depends on the input of the `units` parameter but defaults to meters.

Please also look at the parameters in the official API docs:
https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/json/post
or the isochrones example of the JS package:
https://github.com/GIScience/openrouteservice-js
