### ISSUE TITLE
Add documentation for structured geocoding api

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-docs#8]
Add documentation for using the structured geocoding.
All parameters are passed as json in the querystring using the same endpoint as the normal geocoding:
.../geocode?query={...}
where options (at least one must be provided) in the json are:
address,
neighbourhood,
borough,
locality,
county,
region,
postalcode,
country

So to search for Berliner Straße in Heidelberg, you would use:
../geocode?query={"address":"Berliner Straße","locality":"Heidelberg"}
As always, all characters (including the {} and : ) need to be encoded for transmission.

documentation for the Pelias API structured geocdoing can be found at https://mapzen.com/documentation/search/structured-geocoding/

**Comment by TheGreatRefrigerator** [comment]
Done in 5493f927ff1ec9886f4f1b11cb3a1e199f1eb4e2
