### ISSUE TITLE
Add description for TrailDifficulty extra_info

### ISSUE THREAD

**Issue by Rungee** [GIScience/openrouteservice-docs#9]
In version 4.2, a new extra called "TrailDifficulty" has been added.
This type provides information about trails difficulty for [hiking](http://wiki.openstreetmap.org/wiki/Key:sac_scale) as well as for [mountain-biking](http://wiki.openstreetmap.org/wiki/Key:mtb:scale). Possible values are 1-6, value 0 means no data.

**Comment by TheGreatRefrigerator** [comment]
@Rungee with 6 as most difficult ?

**Comment by Rungee** [comment]
> @Rungee with 6 as most difficult ?
yes, correct.
